import test from 'node:test'; import assert from 'node:assert/strict';
const extractUrl = body => { const v=body.trim(); if (!v.toLowerCase().startsWith('http://') && !v.toLowerCase().startsWith('https://')) return null; if (v.includes(' ')) return null; try { return new URL(v).href; } catch { return null; } };
const hostname = url => { const h=new URL(url).hostname.toLowerCase(); return h.startsWith('www.') ? h.slice(4) : h; };
const cleanTitle = v => v.replace(/\s+/g,' ').replace(/[\\/:#?%*|<>"\x00-\x1f]/g,' ').trim().replace(/\s+/g,' ').slice(0,180);
const targetName = (url, title) => { const h=hostname(url); const t=cleanTitle(title); return t ? `${h} — ${t}` : ''; };
const targetPath = (source, desired) => { const i=source.lastIndexOf('/'); return i > -1 ? `${source.slice(0,i)}/${desired}.md` : `${desired}.md`; };
test('accepts exactly one URL with whitespace', () => assert.equal(extractUrl('  https://www.docs.example.com/a  '), 'https://www.docs.example.com/a'));
test('rejects additional content and malformed URLs', () => { assert.equal(extractUrl('https://example.com more'), null); assert.equal(extractUrl('not a url'), null); });
test('normalizes host and title', () => { assert.equal(hostname('https://WWW.Example.com/x'), 'example.com'); assert.equal(cleanTitle(' A B:/C '), 'A B C'); });
test('builds a safe target name and preserves the source folder', () => { const name=targetName('https://www.example.com/x','A/B: guide'); assert.equal(name,'example.com — A B guide'); assert.equal(targetPath('Projects/Inbox/old.md',name),'Projects/Inbox/example.com — A B guide.md'); });
test('uses vault root when source has no folder', () => assert.equal(targetPath('old.md','example.com — Home'),'example.com — Home.md'));
test('does not create a name when the fetched title is empty', () => assert.equal(targetName('https://example.com','   '),''));
